---
- name: "Ensure password reuse is limited "
  lineinfile:
      path: /etc/pam.d/common-password
      regexp: '^password\s+\[success=1\s+default=ignore\]\s+pam_unix\.so\s+obscure\s+use_authtok\s+try_first_pass\s+yescrypt'
      line: "password        [success=1 default=ignore]      pam_unix.so obscure use_authtok try_first_pass yescrypt remember=3"
      state: present

